### ISSUE TITLE
Huskylens I2C disconnecting

### ISSUE THREAD

**Issue by lenkaiser** [NVL-Project/huskylens_stm32#1]
Hi, since you have worked with STM32 in combination with the Huskylens I was hoping you could help me or maybe had the same experience. When I run the code on an Arduino Uno everything works fine. But when I run the code on my Nucleo F401-RE it has a lot of issues with connecting and once it connects it disconnects after a couple of seconds. I'm just running the HUSKYLENS_I2C.ino example here.

```
21:38:42.772 -> Block:xCenter=160,yCenter=112,width=224,height=224,ID=0
21:38:42.836 -> ###########
21:38:42.836 -> Block:xCenter=160,yCenter=112,width=224,height=224,ID=0
21:38:42.900 -> ###########
21:38:42.900 -> Block:xCenter=160,yCenter###########
21:38:43.500 -> Block:xCenter=160,yCenter=112,width=224,height=224,ID=0
21:38:43.597 -> Fail to request data from HUSKYLENS, recheck the connection!
21:38:43.727 -> Fail to request data from HUSKYLENS, recheck the connection!
21:38:43.859 -> Fail to request data from HUSKYLENS, recheck the connection!
21:38:43.988 -> Fail to request data from HUSKYLENS, recheck the connection!
21:38:44.084 -> Fail to request data from HUSKYLENS, recheck the connection!
```

**Comment by NVL-Project** [comment]
Hello, after resetting, the same problem continues to occur?

**Comment by lenkaiser** [comment]
Yes, it’s very inconsistent. Sometimes it takes 10+ resets for it to connect for just 3 seconds. While with the Arduino Uno this is not a problem.

An alternative is to use RX/TX but I also use a Nextion display and it can’t handle both on different SoftwareSerial pins.

**Comment by NVL-Project** [comment]
Have you installed a pull up on the SDA and SCL pins, if not, install a 4k7 resistor on both pins with VCC 3.3V

If you use the UART pin (RX/TX) on the STM, it's very possible, there are 3 UART pins on the Nucleo F401-RE so there's no need to use SoftwareSerial.

**Comment by lenkaiser** [comment]
No I directly connected the pinout from the Huskylens to the SDA/SCL pins on the board. I found some docs on how to install this. Thanks for the advice!

**Comment by NVL-Project** [comment]
OK, glad to help you

**Comment by lenkaiser** [comment]
I just tested it, and it works. Thanks so much for the help!

**Comment by lenkaiser** [comment]
I know this is the wrong thread but I was hoping you might have an idea for this. On the Nucleo F401-RE you can use USB to power the board and VIN. When I power the board through VIN the SDA/SCL never connects even though I measure the same voltage as when I use USB power. I checked and if I disable the `while(huskylens.begin(Wire))` it will continue to the loop function on VIN power.

**Comment by NVL-Project** [comment]
I assume that the external power supply is not good, it could be low current or bad voltage.  Does it use a power supply with what specs (voltage & current)?

**Comment by lenkaiser** [comment]
I tried multiple power supplies and they all result in the same. Here's the interesting part; If I power the board via VIN it turns on, but it doesn't connect. Once I connect the USB it suddenly connects. When I remove the VIN the board powers down. Suggesting that USB doesn't power the board at all it just triggers something which makes SDA/SCL work?

**Comment by NVL-Project** [comment]
What voltage value do you have on the VIN?

**Comment by lenkaiser** [comment]
With my test setup (breadboard) 7V+ and my actual setup it's a 12V. According to the manual VIN must be between 7V and 12V. And on the SDA/SCL pins I measure around ~4.7V which is the same as when I connect it via USB.

**Comment by NVL-Project** [comment]
Has the configuration in JP5 been changed? If using an EXT Power Supply, the configuration is jumpers 2 & 3. The default is 1 & 2 so the board works when using USB only

**Comment by lenkaiser** [comment]
Yes, if I don't, the external power doesn't work. So what I have is JP5 is set to 2&3, I power the board, no connection with SDA/SCL. I change nothing just plug in the USB connector and at that point SDA/SCL connects instantly. The same way as if I power the board with JP5 set to 1&2 and I use USB to power the board.

Note that I tried to use VCC for pull up resistors both from the board (ext power and usb power) and external power supply. All variants work as along as USB is connected.
